disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'realexblue'               # twitter.com/YOUR_TWITTER_ID
  github = 'iamalexblue'                 # github.com/YOUR_GITHUB_ID
  instagram = 'iamalexblue'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'csjbyebd'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'https://mastodon.social/@realexblue'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://github.com/iamalexblue/jsDelivrCDN/blob/master/static/iamalex.blue-cover.new.jpeg'                 # gravatar email or image url
  name = '从今夜白'
  bio = '你的气质里，藏着你读过的书、走过的路和爱过的人。'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally

  # giscus
[params.giscus]
  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
  repoId = 'YOUR_GISCUS_REPO_ID'
  category = 'YOUR__GISCUS_CATEGORY'
  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'